### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by franky47** [Franky47/stravels#1]
## Strava API
- [ ] Merge api and oauthApi in strava API service
- [x] Handle pagination in activities
- [x] ~~Add `end of data` support to prevent further requests~~
- [x] ~~Improve default page (starts at 1)~~
- [x] ~~Improve state shape to minimise shape conversion~~

## Sagas
- [ ] In the "pull to refresh" saga, perform the request first, then if it succeeds, wipe and replace the received data. This will allow to retain data if the connection is bad, the server is down or we've been rate-limited.

## UI
- [ ] Add state debugging view
- [ ] In the activities list, make the separator line between same day activities dash or dots.
- [ ] Display a filter icon on toolbar in the activity list. Trigger a modal or a large drop-down ? Moving to another view might be confusing.
- [ ] Fix size support in map thumbnail.
- [ ] Add animation for stats items when text is changing (old value moves down with opacity down while new values comes down from the top with opacity up)
- [ ] Add animation for the progress bar, color linear and position by stretching leading edge first to final location then trailing edge catching back). When disappearing, fade out ?
- [x] Fix status bar colors on Android (add `shaded` main)
- [x] Make toolbar button clickable area larger
- [x] `wont-fix` ~~Add option in the settings to opt out of telemetry on behalf of Mapbox, and that will have to be added to the terms and conditions and privacy policy.~~

## UX
- [ ] Add filter for commutes (use briefcase icon, business-center or work)
- [ ] Merge activities by day in the stats, especially for averages, to avoid running average distance / moving time when doing multiple small trips in one day.
- [x] Add swipe in the stats banner to move to the next/previous segment. Use navigation to send the current activity being viewed.
- [x] When focusing on a segment, tap close to the end point to go to the next segment (start for previous), and tap "outside" (away from the line, threshold TBD) to return to summary.

**Comment by Franky47** [comment]
Todo: in the wipe saga, perform the request first, then if it succeeds, wipe and replace the received data. This will allow to retain data if the connection is bad, the server is down or we've been rate-limited.

**Comment by Franky47** [comment]
Add swipe in the stats banner to move to the next/previous segment. Use navigation to send the current activity being viewed. Merge activities by day?

**Comment by Franky47** [comment]
Merge activities by day in the stats, especially for averages, to avoid running average distance / moving time when doing multiple small trips in one day.

**Comment by Franky47** [comment]
Add filter for commutes (use briefcase icon,  `business-center` or `work`)

**Comment by Franky47** [comment]
Display a filter icon on toolbar in the activity list. Trigger a modal or a large drop-down ? Moving to another view might be confusing.

**Comment by franky47** [comment]
Clear fetching on startup persist, or better: filter persist to keep only:
```
{
  strava: {
    oauth: {
      token: 'foobareggspam'
    },
    activities: {
      data: [
        { id: 12, name: 'foo' },
        { id: 42, name: 'bar' }
      ],
      eof: true
    }
  }
}
```

**Comment by Franky47** [comment]
Fix time display in the stats

**Comment by Franky47** [comment]
See why the padding is not consistent on android

**Comment by franky47** [comment]
Stats animation (vertical enter/leave) might be awkward with swipe

**Comment by franky47** [comment]
Make the start/end markers non-clickable, or just remove them completely

**Comment by franky47** [comment]
Put the "back to summary" button away from "reset heading"

**Comment by franky47** [comment]
Add a 'clear selection’ button in the select activities toolbar

**Comment by Franky47** [comment]
Make the progress bar segments proportional to the distance. In the summary, display all segments to see the proportions.

**Comment by Franky47** [comment]
When swiping, loop back to summary after last segment. Swiping right (previous) from summary goes to the last segment

**Comment by franky47** [comment]
Fix pagination in the API

**Comment by franky47** [comment]
onEndReached displays two spinners, the header one triggered by the refreshing flag on the list, and the footer made visible
